# Copyright (c) Ontic. (http://www.ontic.com.au). All rights reserved.
# See the COPYING file bundled with this package for license details.

---

- name: 'Certbot | Include OS-specific variables.'
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'
    - 'default.yml'
  tags:
    - 'certbot'
    - 'certbot-package'
    - 'certbot-configure'
    - 'certbot-service'
    - 'package'
    - 'configure'
    - 'service'

- name: 'Certbot | Define Certbot script.'
  set_fact:
    certbot_script: '{{ certbot_package if not certbot_install_from_source else certbot_source_path + "/certbot-auto" }}'
  tags:
    - 'certbot'
    - 'certbot-package'
    - 'certbot-configure'
    - 'certbot-service'
    - 'package'
    - 'configure'
    - 'service'

- name: 'Certbot | Define Certbot renewal options.'
  set_fact:
    certbot_renewal_options:
      - section: 'renewalparams'
        option: 'authenticator'
        value: 'webroot'
      - section: 'renewalparams'
        option: 'renew_hook'
        value: 'service {{ certbot_web_server_service_name }} reload'
  tags:
    - 'certbot'
    - 'certbot-package'
    - 'certbot-configure'
    - 'certbot-service'
    - 'package'
    - 'configure'
    - 'service'

- name: 'Certbot | Define file name for certificates.'
  set_fact:
    certbot_named_certificates: '{{ certbot_named_certificates|default([]) + [ {"email": item.email, "webroot": item.webroot, "webroot_owner": item.webroot_owner, "domains": item.domains, "file_name": item.domains | first | replace("*.", "")} ] }}'
  with_items: '{{ certbot_certificates }}'
  tags:
    - 'certbot'
    - 'certbot-package'
    - 'certbot-configure'
    - 'certbot-service'
    - 'package'
    - 'configure'
    - 'service'

- import_tasks: 'package.yml'
  tags:
    - 'certbot'
    - 'certbot-package'
    - 'package'

- import_tasks: 'configure.yml'
  tags:
    - 'certbot'
    - 'certbot-configure'
    - 'configure'